### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by marriusco** [charlie1329/Midi-Maker#1]
Are there any docs for the API's in midi.h ? aka;
midiChannelPrefix parameters, cuePoint() setTempo  - relation form 50000 and 120Bpm ???, smtpeOffset ?  timeSignature ?  keySignature ? NoteOn.Off

Thank you.

**Comment by charlie1329** [comment]
Hi!

The `midi.h` file has a link to a page giving all information about each MIDI function. Sadly, this page isn't active any more.
This page seems to give all the same information: http://www.somascape.org/midi/tech/mfile.html

Hope this helps.

**Comment by marriusco** [comment]
Thank you. That is all I need.
